### ISSUE TITLE
Using with Echo?

### ISSUE THREAD

**Issue by gregfr** [alexandrevicenzi/go-sse#15]
Greetings
Is it possible to use this library with Labstatck's Echo framework?
TIA

**Comment by alexandrevicenzi** [comment]
Hi, yes, there's an example [here](https://github.com/alexandrevicenzi/go-sse/blob/master/_examples/echo.go).

**Comment by gregfr** [comment]
Thanks for your answer. I've tried the example but got this error:
`send on closed channel` in sse.go line 82:
```go
		c := newClient(lastEventID, channelName)
		s.addClient <- c
		closeNotify := response.(http.CloseNotifier).CloseNotify()
```

What am I doing wrong?

**Comment by gregfr** [comment]
OK I found it, I left "defer shutdown" in the caller, sorry.
