### ISSUE TITLE
Multiple open tabs communicating

### ISSUE THREAD

**Issue by siredwin** [alexandrevicenzi/go-sse#22]
I have a situation where multiple tabs are communicating with the same server individually.
How do I make sure that each tab gets the right responses? The only thing I know is a dynamically generated tab id.

**Comment by alexandrevicenzi** [comment]
Your question does not make a lot of sense. Each tab will be an individual connection, there's no sharing of resources, each tab is a new socket.

There are two things that you can do this way:

- Each tab get the same messages if they are connected in the same channel
- Each tab get a set of messages if they are in a separate channel

If you want the same messages use the same channel.

```js
e = new EventSource('/events/shared-channel');
e.onmessage = function(event) {
    console.log(event.data);
};
```

If you want to send a set message per-tab use a different channel per tab.

```js
var tabId = sessionStorage.tabID;
e = new EventSource(`/events/channe-{tabId}`);
e.onmessage = function(event) {
    console.log(event.data);
};
```

The above code is just an example, it may not work.

**Comment by siredwin** [comment]
I tried your second example and it did not work.
I ended up converting the payload message into a JSON string with both the message and tab id and it is working. 
I am only listening to one channel
Let me know if this approach is ok?

**Comment by alexandrevicenzi** [comment]
If you have multiple channels you need to publish the message on multiple channels in the server side as well.
