### ISSUE TITLE
*middleware.compressResponseWriter is not http.CloseNotifier:

### ISSUE THREAD

**Issue by Odyssey2247** [alexandrevicenzi/go-sse#8]
Hello!!!
Try using go-see with go-chi as a router by changing:

    http.Handle("/events/", s)

by:

    r.Mount("/events/", s)

but I get the following error:

    panic: interface conversion: *middleware.compressResponseWriter is not http.CloseNotifier: missing method CloseNotify
    ...
    .../github.com/alexandrevicenzi/go-sse/sse.go:82 +0x4c4

I hope you can help me

**Comment by alexandrevicenzi** [comment]
@Odyssey2247 go-chi deprecated CloseNotifier in [#347](https://github.com/go-chi/chi/issues/347), so, to work with go-chi, go-sse should also do this change as http.CloseNotifier is deprecated in Go as well.

You can send a patch to fix this in go-sse, or maybe there's a way to wrap it and trick go-sse.

**Comment by Odyssey2247** [comment]
I found the problem.
the following go-chi middlewares cause the problem:

    r.Use(middleware.Logger)
    r.Use(middleware.Recoverer)
    r.Use(middleware.DefaultCompress)
    r.Use(middleware.NoCache)

changing these middlewares in a group of routes solves the problem
